-------------------------------------------------------------------------------------------------------------
>Platform:     REDIS
>Track ID:     542C0E839CD71C31F2E20DDD3D9A7922
>Error Time:   2024-09-20 21:11:06
>Error File:   F:\Kokomi_API_Main\app\services\api_tracking.py
>Error Name:   REDIS_ERROR_AttributeError
>Error Params: []
>Error Info: 
Traceback (most recent call last):
  File "F:\Kokomi_API_Main\app\services\api_tracking.py", line 41, in record_api_call
    async with redis_client.pipeline() as pipe:
AttributeError: 'NoneType' object has no attribute 'pipeline'

-------------------------------------------------------------------------------------------------------------
